config/routes.rb
Supercanal::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  get "videos/index"

  get "videos/ver"

  match ':programa_id' => 'programas#index', as: :programa
  match 'noticias/:id' => 'noticias#ver', as: :noticia
  
  root to: "inicial#index"

end

app/models/banner.rb
class Banner < ActiveRecord::Base
  attr_accessible :arquivo, :ativo, :titulo
  has_attached_file :arquivo, styles: { mini: "100x100#", normal: '338x240#' },
                    default_style: :normal
  validates_presence_of :titulo
  validates :arquivo, :attachment_presence => true
end

app/models/categoria.rb
class Categoria < ActiveRecord::Base
  attr_accessible :nome
  validates_presence_of :nome
  validates_uniqueness_of :nome
end

app/models/categoria_noticia.rb
class CategoriaNoticia < ActiveRecord::Base
  belongs_to :noticia
  belongs_to :categoria
  # attr_accessible :title, :body
  
end

app/models/imagem_noticia.rb
class ImagemNoticia < ActiveRecord::Base
  belongs_to :noticia
  attr_accessible :arquivo

  has_attached_file :arquivo, styles: { mini: "100x100#", normal: '338x240#' },
                    default_style: :normal
end

app/models/noticia.rb
class Noticia < ActiveRecord::Base
  belongs_to :programa
  
  has_many :video_noticias, class_name: 'VideoNoticia', table_name: 'video_noticias', :dependent => :delete_all, :autosave => true
  has_many :imagem_noticias, class_name: 'ImagemNoticia', table_name: 'imagem_noticias', :dependent => :delete_all, :autosave => true
  has_many :categoria_noticias, :dependent => :delete_all, :autosave => true
  has_many :categorias, :through => :categoria_noticias
  accepts_nested_attributes_for :categorias, :allow_destroy => true
  accepts_nested_attributes_for :video_noticias, :allow_destroy => true
  accepts_nested_attributes_for :imagem_noticias, :allow_destroy => true
  
  has_attached_file :capa, styles: { mini: "100x100#", normal: '338' },
                    default_style: :normal

  attr_accessible :bigode, :conteudo, :publicada_em, :tag, :titulo, 
  :categorias_attributes, :video_noticias_attributes, :imagem_noticias_attributes, 
  :programa_id, :capa

  validates_presence_of :bigode, :conteudo, :publicada_em, :titulo, :programa_id
  
  
  def to_param
    [id,titulo].join('-').parameterize
  end
end

app/models/programa.rb
class Programa < ActiveRecord::Base
  belongs_to :usuario
  attr_accessible :cor, :descricao, :nome, :posicao
  has_many :noticias

  validates_presence_of :nome, :cor, :descricao, :posicao
  
  def to_param
    nome.parameterize
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  attr_accessible :email, :nome, :senha
end

app/models/video_noticia.rb
class VideoNoticia < ActiveRecord::Base
  belongs_to :noticia
  attr_accessible :url, :capa, :titulo, :pagina_inicial
  
  has_attached_file :capa, styles: { mini: "100x100#", normal: '338' },
                    default_style: :normal
                    
  before_save :default_values
  
  def default_values
    if self.titulo.blank?
      self.titulo = self.noticia.titulo
    end
    true
  end
end

app/models/video_programa.rb
class VideoPrograma < ActiveRecord::Base
  belongs_to :programa
  attr_accessible :capa, :titulo, :url, :pagina_inicial
  
  has_attached_file :capa, styles: { mini: "100x100#", normal: '338' },
                    default_style: :normal
  validates_presence_of :titulo, :url
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/inicial_controller.rb
class InicialController < ApplicationController
  def index
    @videos = VideoNoticia.group(:noticia_id).limit(6)
    @noticias = Noticia.limit(6).order('created_at DESC')
  end
end

app/controllers/programas_controller.rb
class ProgramasController < ApplicationController
  def index
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
  end

  def ver
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def menu_programas
    Programa.order(:nome).all
  end
  
  def noticias_laterais
    
  end
end

app/helpers/inicial_helper.rb
module InicialHelper
  
  def slider_inicial
    Banner.limit(3).order('created_at DESC')
  end
end

app/helpers/programas_helper.rb
module ProgramasHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/inicial/index.html.erb
<div class="coluna-esquerda">

  <div id="slider" class="max">
    <div id="slide-holder">
      <div id="slide-runner">
        <div class="wrap-banner">        
          <% slider_inicial.each do |banner| %>
          <%=link_to image_tag(banner.arquivo.url, id: "slide-#{banner.id}"),'#' %>
          <% end %>
          <div id="slide-controls">
            <p id="slide-client" class="text"><strong></strong><span></span></p>
            <p id="slide-nav"></p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div id="ultimos-videos" class="max">
    <h2>Vídeos</h2>
    <% video = @videos.shift  %>
    <div class="video">
    <h3><%= link_to video.noticia.titulo, noticia_path(video.noticia) %></h3>
    <%= link_to image_tag(video.capa.url), noticia_path(video.noticia) %>
    </div>
    <br />
    <% @videos.each do |video| %>
    <div class="video">
    <%= link_to video.noticia.titulo, noticia_path(video.noticia) %>
    <%="<hr />".html_safe if @videos.last != video %>
    </div>
    <% end %>
    
  </div>

  <div id="banners-programas" class="max">
  </div>
  
  <div id="previsao-tempo" class="max">
  </div>
  
  <div id="parceiros" class="max">
  </div>
</div>


<div class="coluna-direita">
  <div id="ultimas-noticias">
    <h2>Útimas notícias</h2>
    <% @noticias.each do |noticia|%>
    <% if noticia == @noticias.first %>
    <h3><%=link_to noticia.titulo, noticia_path(noticia)%></h3>
    <% else %>
    <%=link_to noticia.titulo, noticia_path(noticia)%>
    <% end -%>
    <p><%=link_to noticia.bigode %></p>
    <%="<hr />".html_safe if @noticias.last != noticia %>
    <% end %>
  </div>
  
  <div id="ultima-enquete">
    <h2>Enquete</h2>
  </div>
  
  <div id="voce-no-supercanal">
    <h2>Você no supercanal</h2>
  </div>
  
  <div id="ultimas-vagas-uai">
  </div>
  
  <div id="publicidade-home">
    
  </div>
</div>
<% content_for :header do %>
<script type="text/javascript" charset="utf-8">
if(!window.slider) var slider={};slider.data=<%= slider_inicial.collect{|t| {id: "slide-#{t.id}", client: t.titulo, desc: ""}}.to_json.html_safe %>

$(document).ready(function(){
  
  $('.to-fade').each(function() {
    $(this).hover(
      function() {
        $(this).stop().animate({ opacity: 1.0 });
      },
      function() {
        $(this).stop().animate({ opacity: 0.85 });
      })
    });
})
</script>  
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Supercanal</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="container">
		<div id="cabecalho-interno">
		  <%=render partial: 'shared/menu_topo' %>
			<%=render partial: 'shared/logo_e_conteudo_topo' %>
			<div class="clear"></div>
			<div id="linha-topo"></div>
		</div>
		<div class="clear"></div>
		<div id="conteudo">
  		<div id="conteudo-central">
        <%= yield %>
  		</div>
  		<div id="lateral-direita">
  		  <%=render partial: 'shared/lateral_direita' %>
  		</div>
		</div>
		<div class="clear"></div>
		<div id="rodape">
      <%=render partial: 'shared/rodape' %>
		</div>
	</div>
</body>
</html>

app/views/layouts/inicial.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Super Canal - 24 horas no ar</title>
  <%= stylesheet_link_tag    "inicial", :media => "all" %>
  <%= javascript_include_tag "inicial" %>
  <%= yield(:header) if content_for?(:header)%>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="container">
		<div id="cabecalho">
		  <div id="linha-topo"></div>
		  <%=render partial: 'shared/logo_e_conteudo_topo' %>
			<div class="clear"></div>
			<%=render partial: 'shared/menu_topo' %>
		</div>
		<div class="clear"></div>
		<div id="conteudo">
  		<div id="conteudo-central">
  			<%= yield %>
  		</div>
  		<div id="lateral-direita">
  		  <%=render partial: 'shared/lateral_direita' %>
  		</div>
		</div>
		<div class="clear"></div>
		<div id="rodape">
      <%=render partial: 'shared/rodape' %>
		</div>
	</div>
</body>
</html>

app/views/programas/index.html.erb
<h1>Programas#index</h1>
<p>Find me in app/views/programas/index.html.erb</p>

app/views/shared/_lateral_direita.html.erb
<div class="anuncio-lateral anuncio-grande">
  <h4>Publicidade</h4>
  <img src="/assets/imagem_x.gif" width="250" height="252" />
</div>

<div class="programa-lateral">
  <img src="/assets/lateral-programa-gestao-em-acao.jpg" />
  <img src="/assets/lateral-programa-olho-no-olho.jpg" />
</div>

<% 5.times do %>
<div class="anuncio-lateral anuncio-grande">
  <h4>Publicidade</h4>
  <img src="/assets/imagem_x.gif" width="250" height="120" />
</div>
<% end %>

app/views/shared/_logo_e_conteudo_topo.html.erb
<div id="logo" title="Super Canal - 24 horas no ar"><%=link_to image_tag('logo.png', alt: 'Super Canal - 24 horas no ar'), root_path, title: 'Super Canal - 24 horas no ar' %></div>
<div id="conteudo-topo">
  <div id="busca-topo">
    <%= form_tag method: :get do %>
    <%= text_field_tag :termo, 'pesquisar...' %>
    <%= submit_tag nil, type: :image, src: image_path('botoes/busca.jpg') %>
    <% end %>
  </div>
</div>

app/views/shared/_menu_topo.html.erb
<div id="menu-topo">
  <ul>
    <% menu_programas.each_with_index do |programa,i| %>
      <li><%=link_to programa.nome, programa_path(programa),style: "color:#{programa.cor}"%></li>
      <%=content_tag(:li,'',class: 'separador-menu-topo') if i != (menu_programas.size - 1) %>
    <% end %>
  </ul>
</div>

app/views/videos/index.html.erb
<h1>Videos#index</h1>
<p>Find me in app/views/videos/index.html.erb</p>

app/views/videos/ver.html.erb
<h1>Videos#ver</h1>
<p>Find me in app/views/videos/ver.html.erb</p>